title: ディスクリプティブ・ガール
description: >
  平和で退屈な日常に突如舞い込んだ謎。
  ソースコードに隠された謎に立ち向かうのは、T高校新聞部・茨目奈乃（いばらめなの）と情報処理部の二人。
author: 8amjp
image: site-icon.png
type: novel
card: summary
index: manual
google_analytics: UA-41627578-3
twitter:
  username: 8amjp

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag